image: ruby:2.5

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

stages:
  - build
  - git

variables:
  DEPLOY_DIR: "public"
  REPOSITORY: "github.com/proinfoservice/homepage.git"
  BRANCH: "main"
  REPOSITORY_DIR: "homepage"

build_pages:
  stage: build
  before_script:
    - gem install bundler -v 1.16.4
    - bundle install
  script:
    - bundle exec jekyll build -d $DEPLOY_DIR
    - echo "Список файлов, попавших в сборку:"
    - find $DEPLOY_DIR/.
  artifacts:
    expire_in: 1 hour
    paths:
      - $DEPLOY_DIR
  tags:
    - fast-runners

git_clone:
  stage: git
  script:
    - git clone --single-branch --branch $BRANCH https://$REPOSITORY $REPOSITORY_DIR -q --depth 1
  artifacts:
    expire_in: 1 hour
    paths:
      - $REPOSITORY_DIR
  tags:
    - fast-runners

copy_files:
  stage: git
  script:
    - cd $REPOSITORY_DIR
    - git rm * -r -q
    - cp "../$DEPLOY_DIR" "./" -R -T
    - echo "Список файлов после добавления из сборки:"
    - find .
  needs:
    - job: git_clone
    - build_pages
  artifacts:
    expire_in: 1 hour
    paths:
      - $REPOSITORY_DIR
  tags:
    - fast-runners

git_commit:
  stage: git
  script:
    - cd $REPOSITORY_DIR
    - git config user.email "github@proinfoservice.ru"
    - git config user.name "proinfoservice-admin"
    - git config --global core.safecrlf false
    - git config core.autocrlf false
    - git add -A
    - git commit -am "Update homepage" -q
  needs:
    - job: copy_files
  artifacts:
    expire_in: 1 hour
    paths:
      - $REPOSITORY_DIR
  tags:
    - fast-runners

git_push:
  stage: git
  script:
    - cd $REPOSITORY_DIR
    - git config credential.modalprompt false
    - git push -q https://$DEPLOY_KEY@$REPOSITORY $BRANCH
  needs:
    - job: git_commit
  tags:
    - fast-runners
